spring.application.name=backend

spring.datasource.url=jdbc:mysql://mysql-7781c4c-project-f6fa.f.aivencloud.com:16368/WWW
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_VG1MGcZ67UQmgBwxZrc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect